sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

env:
  - DOCKER_IMAGE2=amela/returnPolicy

install:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE2" .

after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push "$DOCKER_IMAGE2"