kumuluzee:
  name: rso-returnPolicy
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/returnPolicyDS
      connection-url: jdbc:postgresql://192.168.99.100:5434/returnPolicy
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  health:
      checks:
        data-source-health-check:
          jndi-name: jdbc/returnPolicyDS
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    web-instrumentation:
      - name: returnPolicy-endpoint
        url-pattern: /v1/returnPolicy/*
rest-properties:
  external-services:
    returnPolicy-service:
      enabled: true
  healthy: true
