kumuluzee:
  name: returnPolicy
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/ReturnPolicyDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/returnPolicy
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
rest-properties:
  external-services:
    product-service:
      enabled: true
