kumuluzee:
  name: rso-comments
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/commentsDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/comment
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  health:
      checks:
        data-source-health-check:
          jndi-name: jdbc/commentsDS
  cors-filter:
    servlet:
      allow-origin: "*"
rest-properties:
  external-services:
    order-service:
      enabled: true
  healthy: true
