apiVersion: v1
kind: Service
metadata:
  name: return_policy
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: return_policy